trigger:
- arbatel

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: BatchScript@1
  inputs:
    filename: build.cmd
    arguments: NuGet

- task: CopyFiles@2
  inputs:
    SourceFolder: 'bin'
    Contents: |
      *.nupkg
      !*OpenTK.GLWidget*.nupkg
    TargetFolder: '$(Build.ArtifactsStagingDirectory)'

- task: PublishPipelineArtifact@0
  inputs:
    artifactName: 'NuGetPackages'
    targetPath: '$(Build.ArtifactsStagingDirectory)'
